version: '3.7'

services:
  bot:
    image: python:alpine
    container_name: boalo_bot
    build: .
    environment:
      - BOT_API_KEY=
      - ENGINE_URI=
        #postgresql://wowuser:wowpass@localhost:5010/wowdb
      - TELEGRAM_ADMIN_ID=
    volumes:
      - /etc/ocserv:/etc/ocserv
    depends_on:
      - db
  db:
    image: postgres:alpine
    container_name: boalo_db
    restart: always
    environment:
      - POSTGRES_DB=wowdb
      - POSTGRES_USER=wowuser
      - POSTGRES_PASSWORD=wowpass
      - PG_DATA=/var/lib/postgresql/data/pgdata
